services:
  db:
    image: mariadb:11
    container_name: zw_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: zettelwirtschaft
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - zw_db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: zw_app
    restart: always
    depends_on:
      - db
    env_file: .env
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public

  web:
    image: nginx:alpine
    container_name: zw_web
    restart: always
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mercure:
    image: dunglas/mercure
    container_name: zw_mercure
    restart: always
    environment:
      SERVER_NAME: :80
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_JWT_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_JWT_KEY}
      MERCURE_EXTRA_DIRECTIVES: "cors_origins *"
    ports:
      - "${MERCURE_PORT}:80"

volumes:
  zw_db_data: